In [4]:
import numpy as np
import torch

In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [23]:
def tell_tensor(data):
    print(f'data: {data}')
    print(f'shape: {data.shape}')
    print(f'dtype: {data.dtype}')
    print(f'device: {data.device}')
    print(f'stride: {data.stride()}')
    data_cuda = data.cuda()
    print(f'device: {data_cuda.device}')

### tensor 初始化

In [24]:
# from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
tell_tensor(x_data)

data: tensor([[1, 2],
        [3, 4]])
shape: torch.Size([2, 2])
dtype: torch.int64
device: cpu
stride: (2, 1)
device: cuda:0


In [25]:
# from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
tell_tensor(x_np)

data: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
shape: torch.Size([2, 2])
dtype: torch.int32
device: cpu
stride: (2, 1)
device: cuda:0


In [28]:
# anthor tensor
x_one = torch.ones_like(x_np)
tell_tensor(x_one)
x_rand = torch.rand_like(x_np, dtype=torch.float32)
tell_tensor(x_rand)

data: tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
shape: torch.Size([2, 2])
dtype: torch.int32
device: cpu
stride: (2, 1)
device: cuda:0
data: tensor([[0.5899, 0.5108],
        [0.8617, 0.4414]])
shape: torch.Size([2, 2])
dtype: torch.float32
device: cpu
stride: (2, 1)
device: cuda:0


In [30]:
# some api
shape = (3, 3,)
rand_data = torch.rand(shape)
one_data = torch.ones(shape)
tell_tensor(rand_data)
tell_tensor(one_data)

data: tensor([[0.8499, 0.5348, 0.9935],
        [0.9290, 0.8268, 0.2349],
        [0.1043, 0.3614, 0.4428]])
shape: torch.Size([3, 3])
dtype: torch.float32
device: cpu
stride: (3, 1)
device: cuda:0
data: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
shape: torch.Size([3, 3])
dtype: torch.float32
device: cpu
stride: (3, 1)
device: cuda:0


### operation

In [35]:
# index
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [39]:
# join
print(f'shape: {tensor.shape}')
tensor_cat = torch.cat([tensor, tensor, tensor], dim=1)
print(f'shape: {tensor_cat.shape}')

shape: torch.Size([4, 4])
shape: torch.Size([4, 12])


In [40]:
# Arithmetic operations
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [41]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [43]:
# single element
agg = tensor.sum()
print(agg, type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In [46]:
# inplace
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]]) 

tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


### with numpy

In [48]:
# tensor to numpy
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [49]:
# numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
